// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packed_fixed32.proto
// Protobuf C++ Version: 7.35.0-dev

#include "packed_fixed32.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/io/zero_copy_stream_impl_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace asanvalidator {
namespace protobufinput003 {
class PackedFixed32Message::_Internal {
 public:
  using HasBits = decltype(::std::declval<PackedFixed32Message>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PackedFixed32Message, _impl_._has_bits_);
};

constexpr PackedFixed32Message::ParseTableT_ PackedFixed32Message::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(PackedFixed32Message, _impl_._has_bits_),
      0, // no _extensions_
      1, 0,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967294,  // skipmap
      offsetof(ParseTableT_, field_entries),
      1,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallbackLite,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::asanvalidator::protobufinput003::PackedFixed32Message>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // repeated fixed32 nums = 1 [packed = true];
      {::_pbi::TcParser::FastF32P1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(PackedFixed32Message, _impl_.nums_)}},
    }}, {{
      65535, 65535
    }}, {{
      // repeated fixed32 nums = 1 [packed = true];
      {PROTOBUF_FIELD_OFFSET(PackedFixed32Message, _impl_.nums_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedFixed32)},
    }},
    // no aux_entries
    {{
    }},
  };
}


inline constexpr PackedFixed32Message::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        nums_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::asanvalidator::protobufinput003::PackedFixed32Message,
            PROTOBUF_FIELD_OFFSET(::asanvalidator::protobufinput003::PackedFixed32Message, _impl_.nums_)>()
         }
     {}

template <typename>
constexpr PackedFixed32Message::PackedFixed32Message(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::MessageLite(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL PackedFixed32Message::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PackedFixed32Message(arena);
}
constexpr auto PackedFixed32Message::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PackedFixed32Message), alignof(PackedFixed32Message));
}
constexpr auto PackedFixed32Message::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataLite{
      {
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &PackedFixed32Message::MergeImpl,
          ::google::protobuf::MessageLite::GetNewImpl<PackedFixed32Message>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PackedFixed32Message::SharedDtor,
          ::google::protobuf::MessageLite::GetClearImpl<PackedFixed32Message>(), &PackedFixed32Message::ByteSizeLong,
              &PackedFixed32Message::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PackedFixed32Message, _impl_._cached_size_),
          true,
      },
      "asanvalidator.protobufinput003.PackedFixed32Message",
  };
}
struct PackedFixed32MessageGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr PackedFixed32MessageGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 PackedFixed32Message_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(PackedFixed32Message::InternalGenerateClassData_(
            _default, &PackedFixed32Message_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<PackedFixed32Message>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~PackedFixed32MessageGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) PackedFixed32Message _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<PackedFixed32Message>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(PackedFixed32MessageGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 
    #ifdef PROTOBUF_MESSAGE_GLOBALS
    const
    #endif
     PackedFixed32MessageGlobalsTypeInternal PackedFixed32Message_globals_
        #ifdef PROTOBUF_MESSAGE_GLOBALS
        ABSL_ATTRIBUTE_SECTION_VARIABLE(.data.rel.ro)
        #endif  // PROTOBUF_MESSAGE_GLOBALS
        ;
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* PackedFixed32Message_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return PackedFixed32Message_globals_.GetClassData();
#else
  return PackedFixed32Message_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace protobufinput003
}  // namespace asanvalidator
namespace asanvalidator {
namespace protobufinput003 {
// ===================================================================

PackedFixed32Message::PackedFixed32Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, PackedFixed32Message_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:asanvalidator.protobufinput003.PackedFixed32Message)
}
PROTOBUF_NDEBUG_INLINE PackedFixed32Message::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::asanvalidator::protobufinput003::PackedFixed32Message& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        nums_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::asanvalidator::protobufinput003::PackedFixed32Message,
              PROTOBUF_FIELD_OFFSET(::asanvalidator::protobufinput003::PackedFixed32Message, _impl_.nums_)>()
          , from.nums_
        }
     {}

PackedFixed32Message::PackedFixed32Message(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PackedFixed32Message& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::MessageLite(arena, PackedFixed32Message_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::MessageLite(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PackedFixed32Message* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:asanvalidator.protobufinput003.PackedFixed32Message)
}
PROTOBUF_NDEBUG_INLINE PackedFixed32Message::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        nums_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::asanvalidator::protobufinput003::PackedFixed32Message,
            PROTOBUF_FIELD_OFFSET(::asanvalidator::protobufinput003::PackedFixed32Message, _impl_.nums_)>()
         }
     {}

inline void PackedFixed32Message::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PackedFixed32Message::~PackedFixed32Message() {
  // @@protoc_insertion_point(destructor:asanvalidator.protobufinput003.PackedFixed32Message)
  SharedDtor(*this);
}
inline void PackedFixed32Message::SharedDtor(MessageLite& self) {
  PackedFixed32Message& this_ = static_cast<PackedFixed32Message&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::std::string>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataLite PackedFixed32Message_class_data_ =
    PackedFixed32Message::InternalGenerateClassData_(PackedFixed32Message_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PackedFixed32Message::GetClassData() const {
  return PackedFixed32Message_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PackedFixed32Message::GetClassData() const {
  return PackedFixed32Message_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const PackedFixed32Message::ParseTableT_
    PackedFixed32Message::_table_ =
        PackedFixed32Message::InternalGenerateParseTable_(PackedFixed32Message_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void PackedFixed32Message::Clear() {
// @@protoc_insertion_point(message_clear_start:asanvalidator.protobufinput003.PackedFixed32Message)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.nums_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::std::string>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PackedFixed32Message::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PackedFixed32Message& this_ = static_cast<const PackedFixed32Message&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PackedFixed32Message::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PackedFixed32Message& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:asanvalidator.protobufinput003.PackedFixed32Message)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated fixed32 nums = 1 [packed = true];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (this_._internal_nums_size() > 0) {
      target = stream->WriteFixedPacked(1, this_._internal_nums(), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = stream->WriteRaw(
        this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).data(),
        static_cast<int>(this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:asanvalidator.protobufinput003.PackedFixed32Message)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PackedFixed32Message::ByteSizeLong(const MessageLite& base) {
  const PackedFixed32Message& this_ = static_cast<const PackedFixed32Message&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PackedFixed32Message::ByteSizeLong() const {
  const PackedFixed32Message& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:asanvalidator.protobufinput003.PackedFixed32Message)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated fixed32 nums = 1 [packed = true];
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::size_t{4} *
          ::_pbi::FromIntSize(this_._internal_nums_size());
      ::size_t tag_size = data_size == 0
          ? 0
          : 1 + ::_pbi::WireFormatLite::Int32Size(
                              static_cast<::int32_t>(data_size));
      total_size += tag_size + data_size;
    }
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    total_size += this_._internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString).size();
  }
  this_._impl_._cached_size_.Set(::_pbi::ToCachedSize(total_size));
  return total_size;
}

void PackedFixed32Message::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<PackedFixed32Message*>(&to_msg);
  auto& from = static_cast<const PackedFixed32Message&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:asanvalidator.protobufinput003.PackedFixed32Message)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_nums()->MergeFrom(from._internal_nums());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::std::string>(
      from._internal_metadata_);
}

void PackedFixed32Message::CopyFrom(const PackedFixed32Message& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:asanvalidator.protobufinput003.PackedFixed32Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PackedFixed32Message::InternalSwap(PackedFixed32Message* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.nums_.InternalSwap(&other->_impl_.nums_);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobufinput003
}  // namespace asanvalidator
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
