// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: packed_fixed32.proto
// Protobuf C++ Version: 7.35.0-dev

#ifndef packed_5ffixed32_2eproto_2epb_2eh
#define packed_5ffixed32_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

// clang-format off
#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 7035000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_packed_5ffixed32_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_packed_5ffixed32_2eproto {
  static const ::uint32_t offsets[];
};
namespace asanvalidator {
namespace protobufinput003 {
class PackedFixed32Message;
struct PackedFixed32MessageGlobalsTypeInternal;
#ifndef PROTOBUF_MESSAGE_GLOBALS
extern PackedFixed32MessageGlobalsTypeInternal PackedFixed32Message_globals_;
extern const ::google::protobuf::internal::ClassDataLite PackedFixed32Message_class_data_;
#else
extern const PackedFixed32MessageGlobalsTypeInternal PackedFixed32Message_globals_;
#endif  // PROTOBUF_MESSAGE_GLOBALS
}  // namespace protobufinput003
}  // namespace asanvalidator
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace asanvalidator {
namespace protobufinput003 {

// ===================================================================


// -------------------------------------------------------------------

class  PROTOBUF_FUTURE_ADD_EARLY_WARN_UNUSED PackedFixed32Message final : public ::google::protobuf::MessageLite
/* @@protoc_insertion_point(class_definition:asanvalidator.protobufinput003.PackedFixed32Message) */ {
 public:
  inline PackedFixed32Message() : PackedFixed32Message(nullptr) {}
  ~PackedFixed32Message() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PackedFixed32Message* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PackedFixed32Message));
  }
#endif

  template <typename = void>
  explicit constexpr PackedFixed32Message(::google::protobuf::internal::ConstantInitialized,
                           const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
                               class_data);

  inline PackedFixed32Message(const PackedFixed32Message& from) : PackedFixed32Message(nullptr, from) {}
  inline PackedFixed32Message(PackedFixed32Message&& from) noexcept : PackedFixed32Message(nullptr, ::std::move(from)) {}
  inline PackedFixed32Message& operator=(const PackedFixed32Message& from) {
    CopyFrom(from);
    return *this;
  }
  inline PackedFixed32Message& operator=(PackedFixed32Message&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  [[nodiscard]] inline const ::std::string& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::std::string>(::google::protobuf::internal::GetEmptyString);
  }
  [[nodiscard]] inline ::std::string* PROTOBUF_NONNULL
  mutable_unknown_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::std::string>();
  }

  [[nodiscard]] static const PackedFixed32Message& default_instance() {
    return *::google::protobuf::internal::MessageGlobalsBase::ToDefaultInstance<PackedFixed32Message>(&PackedFixed32Message_globals_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(PackedFixed32Message& a, PackedFixed32Message& b) { a.Swap(&b); }
  inline void Swap(PackedFixed32Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PackedFixed32Message* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  [[nodiscard]] PackedFixed32Message* PROTOBUF_NONNULL
  New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::MessageLite::DefaultConstruct<PackedFixed32Message>(arena);
  }
  void CopyFrom(const PackedFixed32Message& from);
  void MergeFrom(const PackedFixed32Message& from) { PackedFixed32Message::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  [[nodiscard]] bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  [[nodiscard]] static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  [[nodiscard]] static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  [[nodiscard]] ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] ::size_t ByteSizeLong() const final;
  [[nodiscard]] ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  [[nodiscard]] int GetCachedSize() const {
    return _impl_._cached_size_.Get();
  }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PackedFixed32Message* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "asanvalidator.protobufinput003.PackedFixed32Message"; }

  explicit PackedFixed32Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PackedFixed32Message(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PackedFixed32Message& from);
  PackedFixed32Message(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PackedFixed32Message&& from) noexcept
      : PackedFixed32Message(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_(
      const MessageLite& prototype,
      const ::google::protobuf::internal::TcParseTableBase* PROTOBUF_NULLABLE tc_table = nullptr);

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNumsFieldNumber = 1,
  };
  // repeated fixed32 nums = 1 [packed = true];
  [[nodiscard]] int nums_size()
      const;
  private:
  int _internal_nums_size() const;

  public:
  void clear_nums() ;
  [[nodiscard]] ::uint32_t nums(int index) const;
  void set_nums(int index, ::uint32_t value);
  void add_nums(::uint32_t value);
  [[nodiscard]] const ::google::protobuf::RepeatedField<::uint32_t>& nums()
      const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_nums();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_nums() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_nums();

  public:
  // @@protoc_insertion_point(class_scope:asanvalidator.protobufinput003.PackedFixed32Message)
 private:
  class _Internal;
  using ParseTableT_ =
      ::google::protobuf::internal::TcParseTable<0, 1,
                          0, 0,
                          2>;
  static constexpr ParseTableT_ InternalGenerateParseTable_(
      const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL class_data);
  friend class ::google::protobuf::internal::TcParser;
  #ifndef PROTOBUF_MESSAGE_GLOBALS
  static const ParseTableT_ _table_;
  #endif

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  friend ::google::protobuf::internal::PrivateAccess;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::InternalVisibility visibility,
                                    ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PackedFixed32Message& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> nums_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_packed_5ffixed32_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PackedFixed32Message

// repeated fixed32 nums = 1 [packed = true];
inline int PackedFixed32Message::_internal_nums_size() const {
  return _internal_nums().size();
}
inline int PackedFixed32Message::nums_size() const {
  return _internal_nums_size();
}
inline void PackedFixed32Message::clear_nums() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nums_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
inline ::uint32_t PackedFixed32Message::nums(int index) const {
  // @@protoc_insertion_point(field_get:asanvalidator.protobufinput003.PackedFixed32Message.nums)
  return _internal_nums().Get(index);
}
inline void PackedFixed32Message::set_nums(int index, ::uint32_t value) {
  _internal_mutable_nums()->Set(index, value);
  // @@protoc_insertion_point(field_set:asanvalidator.protobufinput003.PackedFixed32Message.nums)
}
inline void PackedFixed32Message::add_nums(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_nums()
      ->InternalAddWithArena<const ::google::protobuf::MessageLite*>(
          internal_visibility(), this, value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:asanvalidator.protobufinput003.PackedFixed32Message.nums)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& PackedFixed32Message::nums() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:asanvalidator.protobufinput003.PackedFixed32Message.nums)
  return _internal_nums();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL PackedFixed32Message::mutable_nums()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:asanvalidator.protobufinput003.PackedFixed32Message.nums)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_nums();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
PackedFixed32Message::_internal_nums() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nums_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
PackedFixed32Message::_internal_mutable_nums() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.nums_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace protobufinput003
}  // namespace asanvalidator


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"
// clang-format on

#endif  // packed_5ffixed32_2eproto_2epb_2eh
